name: BetterGenerator
description: A bukkit world generator that's better than the default one.
version: 1.0
main: org.bettergenteam.bettergen.bukkitplugin.BetterGenPlugin
load: STARTUP
author: jtjj222
authors: [codename_b, sd5, Kodfod, NSArray, escortkeel]